sudo: required
language: generic
services:
- docker
os:
- linux
dist: trusty
before_script:
- |
  docker pull n1nj4sec/tc-windows & docker pull n1nj4sec/tc-linux32 &
  docker pull n1nj4sec/tc-linux64 & docker pull n1nj4sec/tc-android
script:
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH;
  fi`
- cd $TRAVIS_BUILD_DIR && ./build-docker.sh
- ls -l $TRAVIS_BUILD_DIR/pupy/payload_templates/pupyx64*.lin
- ls -l $TRAVIS_BUILD_DIR/pupy/payload_templates/pupyx64*.so
- ls -l $TRAVIS_BUILD_DIR/pupy/payload_templates/pupyx64*.dll
- ls -l $TRAVIS_BUILD_DIR/pupy/payload_templates/pupyx64*.exe
- ls -l $TRAVIS_BUILD_DIR/pupy/payload_templates/pupyx86*.lin
- ls -l $TRAVIS_BUILD_DIR/pupy/payload_templates/pupyx86*.so
- ls -l $TRAVIS_BUILD_DIR/pupy/payload_templates/pupyx86*.dll
- ls -l $TRAVIS_BUILD_DIR/pupy/payload_templates/pupyx86*.exe
- ls -l $TRAVIS_BUILD_DIR/pupy/payload_templates/pupy.apk
- ls -l $TRAVIS_BUILD_DIR/pupy/payload_templates/windows-amd64.zip
- ls -l $TRAVIS_BUILD_DIR/pupy/payload_templates/windows-x86.zip
- ls -l $TRAVIS_BUILD_DIR/pupy/payload_templates/linux-amd64.zip
- ls -l $TRAVIS_BUILD_DIR/pupy/payload_templates/linux-x86.zip
after_success:
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH;
  fi`
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- cd $TRAVIS_BUILD_DIR/pupy && docker push n1nj4sec/pupy:$TAG >/dev/null
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: NB7iHtJX41G0hHj+WHxYX1C+a/jIIzsLOB8nswG0HB2WVB1bYtG9hsMzl5htR53+IhwGK8VL6m3Ds83rslAoNYttGXAmAT/xfftvRGx9p0OvOHo6vB4fIw40OAS0Z3YqQNoRDy992HQZqE7w8jY75eos7ia1HLqsbN/x84PcEX5VfAJRd8igYe5FAcuDvHtbtNmzLRf4+CILZZYQb7NV/vN2m5L4C6XcZBlxkT5DIGF29T6OLsoqsv9eiWKCy4VHF+1VUUoQDR6mPxEB2MN8c930V0/YFfvIC2PgfEkvBzEItBIN2FDCmj+wqXeCQ/+qdeHPK8J7sHLtQbBvhRFruQcjQ5R8/0E62w/P5U9ETuz6afRqRd/Nx7Xy5Ah4aaN9STc0nnDaD15bNBqptfroNlpDhZgr61ZSpe9Hxr+fYcX6GrVsAa1kChU/GqrBU2pJyO0Qllwj8m74orTaZHfZBzDU//a5wOdVc19GMMEYAz2wGvXYQ4W8pyAj995VqXWlxrXGhl9HySPv8coNorVh7xXsZOD4+e/zkiAXoYFsnfT7KoX/kjIwRkEHTAg4RbEPmGbREE3whx5nM93r5Ol0/G/Tu5hyoPvfLcaIEHIa7fxG0rABS6yMWCvR8aoHUBXcN425QRBCdK7O0mRkFay+B3sSz6Wm4pKnS63rKJNyEfc=
  - secure: nh39LRyxah62YdYkIaGqJtq3X+NxyBvbMt4BBq+XlGM/sRBCY6pBlFk699Df4gAK/d8nXVNIfxQRy/rGM7XPll6VBhrkGtBFMLkvBX1TkFeLKeszyYopRvrVhIhOTmDHAoBQPW5vmC9n2RNdGqYqDwqyHosxtoJ4D//Q87DIJgOVOVydttbDP2nq3kduAiBH2qvI6IYT1ZG7X6qQZMQ/UWs6r2w57P3SoznDO3mq55ndvE4uE3JC54T5K0v2D+YYxsNx5v8KN9ngeijn3Gru5W8hUzomA9JuTO7I/TzJilansQEGUcfwT19k5wKF1im5iUelm+LEM6KpYaEN2NlcvdBQDP58ZC/kYUuM6Ctxqy/35GThFQCAF67p8DhBs6yXW5KUpRFms1IW8NjwryvcEx3FRr+PWT+hd1b6V6cubQhX4TTSPrV1wqUwe3SZRNwVppy+97zrnivWETV1Q2iRwWB6IB2t+MTcjEvo96mlas8OCWa80MniJ6D7JzxYoZ3dJZenrCjCSIMaY9nohPsBQyVXak8rATO1iHT5u/F9JqTGeKqir04HUoYp06DvvLve+EsXkwnzJsdCYUdd+gIpKYcW715xUX7ibSRuYtIaXfOaysUB4MEAycJATwcDlYCrLzwtJlZH1QhtNSQnUSD8rDh6dwN4QjbZuUaKAGhJJiU=
before_deploy:
  - tar -C $TRAVIS_BUILD_DIR/pupy -Jcf $TRAVIS_BUILD_DIR/payload_templates.txz payload_templates
deploy:
  provider: releases
  api_key:
    secure: E3nJgSrYLIIil6eqP0h0c67Ktaw9QN7IfNDsaIuQwstZE/kBIJe9DIY93oaN+1soosknXHm/dsLeraNZVYXJbsoE9lPuDzOdC2sBq09xAR+ZRFXdtUMXtMDv816v2ZsdHZbfbNvm5ucixE9eGXDGPpDYcJRliHpAFPavysHL3lvF0dem1rI2RQsB0LGRYGOVFwjpdpqFITZs1BZxq/clXbqBLBnJO30D3LUdbXWYCqC4M4fMIIQOsWZRLGu8JgD6stmB8t+ve7XcXy4JhE6jFNgzMP6DHYoloobeUWWk6RbsAPs4j3UYbYFCsuow+JJ9iaXP0sgv8gST3nqjZtF1xiRVYOdqTa2MIAkGIuOmH1otl55C6UuXdIZGd6SPOKlKC3ccB92KcDy+7h5QcH16mFqZKsOkYRAE4izaE9GyWejpFxlnqOZGLwN8AKsf/zpWq4bRbEAYLWayi1KYNzGlFwsbdf7BWZJ90JWmVpf1AcJ92sbNexxkoW47Jm+Ir264ZK72IWLdE9PYkNUi5wt6IhsHsshdVlUa0p3qvIgBeWdfm+fgcm7qyJbCp37SFgbYmcs4+9U9B75lPpYR7RZOdGh3NGcREFbzYVz+VpPOaDGEJ4mBWn3DXcLtnjBG4q28/eDSkvrq1QK1g8+urzml6KYHaH738tRbjV97YsHsAvM=
  file:
  - "$TRAVIS_BUILD_DIR/payload_templates.txz"
  skip_cleanup: true
  on:
    repo: n1nj4sec/pupy
    tags: true
